### ISSUE TITLE
Patched?!

### ISSUE THREAD

**Issue by Helixable** [DaveDuck321/KahootSmasher-NodeJS#15]
I've been working a bit on my modification of this project. I think we've been patched. Check out this demo: https://repl.it/@Helixable/Hackoot
If you click run and you enter in the pin and amount of bots, there's an error. :(
Any Idea on what's going on?

**Comment by Helixable** [comment]
Just check back after an hour and it's working now. Sorry.

**Comment by Helixable** [comment]
It's acting up again.

**Comment by DaveDuck321** [comment]
Can you please describe the issue and how to reproduce it?

**Comment by Helixable** [comment]
Visit the demo link I sent you, Wait for the page to load completely. Then press "restart" on the top. The console will print "Server Online" when it has been restarted. Host a simple kahoot game and put the pin/amount of bots in. Look at the error in the console. It only happens sometimes. Btw, I added the ability to start smashing remotely from a Post request. :)

**Comment by DaveDuck321** [comment]
Does this same error occur when you clone and run this repo directly from the github without your modifications?
Also if you've added any features that you think would benefit the project please submit a pull request instead of linking to another hosting service, it is unreasonable to expect me to debug code that is not part of the project.
I'm closing this issue for now, but if this is also a problem with the head repository feel free to reopen.
